### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by bigspawn** [bigspawn/AlterportalParser#1]
- [x] Add processing for exception on load photo
- [x] Don't add empty fields
- [ ] Add link to Google play
- [x] Don't post empy fields for news type
- [ ] Add bot notification if error happen
